spring:
  application:
    name: ghost-api
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/test
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8762
logging:
  level:
   root: error
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/